### ISSUE TITLE
Usernames from fragment not founded

### ISSUE THREAD

**Issue by moshe-coh** [pyrogram/pyrogram#1232] opened 2023-03-08 11:03 UTC
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When I'm trying to use the method get_chat on an username that assigned to telegram from fragment.com it raised KeyError like: 'Username not found: fragments'

### Steps to reproduce

I think the description of the issue is enough 🙂

### Code example

```python
from pyrogram import Client

app = Client("my")
print(app.get_chat("fragments"))
```

### Logs

```shell
KeyError: 'Username not found: fragments'
```

**Comment by delivrance** [comment] 2023-03-11 15:50
Duplicate of #1231 (which has been addressed already).

**Closed by delivrance** 2023-03-11 15:50 UTC
