### ISSUE TITLE
download_media to BytesIO

### ISSUE THREAD

**Issue by WhiteApfel** [pyrogram/pyrogram#579] opened 2021-01-02 09:16 UTC
## Checklist
- [x] I believe the idea is awesome and would benefit the library.
- [x] I have searched in the issue tracker for similar requests, including closed ones.

## Description
It would be cool to be able not to save the file to disk, but to receive a BytesIO object(s) in response.

**Comment by delivrance** [comment] 2022-03-02 17:19
Duplicate of #284.

**Closed by delivrance** 2022-03-02 17:19 UTC
Labels: enhancement
