### ISSUE TITLE
Stuck in a loop after a network failure

### ISSUE THREAD

**Issue by dogtopus** [pyrogram/pyrogram#25] opened 2018-02-21 21:57 UTC
Instead of automatically recovering or gracefully exiting with error, Pyrogram seems to stuck in a loop and stops responding to updates and even Ctrl+C events after network changes or failures

**Comment by delivrance** [comment] 2018-02-21 22:04
Hi. Can you reproduce this consistently?

**Comment by dogtopus** [comment] 2018-02-22 15:34
Given the fact that I cannot reproduce this behavior manually anymore, I would say it is occasional.

**Comment by delivrance** [comment] 2018-02-22 15:37
@dogtopus What version were you using? I've spotted some weird behaviours that may trigger this and I've fixed them accordingly

**Comment by dogtopus** [comment] 2018-02-22 19:40
0.5.0 IIRC

**Comment by delivrance** [comment] 2018-02-22 19:47
@dogtopus Also what's the OS/distro and your python version?

**Comment by delivrance** [comment] 2018-02-25 14:05
Closing due to no reply. Feel free to re-open if you can reproduce this after you update to v0.6.1+. Your version is too old and doesn't contain the fix.

**Closed by delivrance** 2018-02-25 14:05 UTC
