### ISSUE TITLE
Incorrect Method Name in Documentation for get_chat_history_count

### ISSUE THREAD

**Issue by cl7paBka** [pyrogram/pyrogram#1445] opened 2024-08-03 19:11 UTC
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [ ] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

There is a small typo in the documentation for the `get_chat_history_count` method [here](https://docs.pyrogram.org/api/methods/get_chat_history_count#pyrogram.Client.get_chat_history_count). 
The example shows the incorrect method name: 

> await **app.get_history_count(chat_id)**

The correct example is: 

> await **app.get_chat_history_count(chat_id)**

### Steps to reproduce

Open this [link](https://docs.pyrogram.org/api/methods/get_chat_history_count#pyrogram.Client.get_chat_history_count) (Pyrogram Documentation for **Available Methods** » **get_chat_history_count()**), look at the top of the page for the method name and at the bottom of the page in the EXAMPLE section.

### Code example

```python
import asyncio
from pyrogram import Client

async def main():
    async with Client("me") as app:
        count_messages = await app.get_history_count("me")
        print(count_messages)

if __name__ == "__main__":
    asyncio.run(main())
```

### Logs

```shell
AttributeError: 'Client' object has no attribute 'get_history_count'. Did you mean: 'get_chat_history_count'?
```

**Comment by SpEcHiDe** [comment] 2024-08-04 03:38
Duplicate of #1288

**Closed** 2024-08-06 17:26 UTC
