### ISSUE TITLE
Auth Problem [406 UPDATE_APP_TO_LOGIN]

### ISSUE THREAD

**Issue by MdHazrat8361** [pyrogram/pyrogram#795] opened 2021-12-01 06:52 UTC
406 UPDATE_APP_TO_LOGIN
when i try to create a new session , i face this except .

**Comment by RememberTheAir** [comment] 2021-12-01 07:26
Duplicate of  #794

**Comment by theadbothostpro** [comment] 2021-12-01 10:46
How to solve this error?

**Comment by joaopedrolourencoaffonso** [comment] 2021-12-01 12:35
We at Telethon are having the [same](https://github.com/LonamiWebs/Telethon/issues/3215) problem.

**Closed** 2021-12-01 12:38 UTC
