### ISSUE TITLE
400 MESSAGE_EMPTY with private channel and restrict saving content option is enabled

### ISSUE THREAD

**Issue by C3FF995BAE4** [pyrogram/pyrogram#1254] opened 2023-04-09 05:57 UTC
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When I try to get media from restrict saving content option enabled private channel, it says below.
Error: Telegram says: [400 MESSAGE_EMPTY]
- The message sent is empty or contains invalid characters (caused by "messages.SendMessage")

Downloading from public channel is working well.
Perhaps Telegram has tweaked something.

There was a same problem with Telethon in the past: https://github.com/LonamiWebs/Telethon/issues/3264

### Steps to reproduce

Run a code with below two project:
https://github.com/bipinkrish/Save-Restricted-Bot
https://github.com/vasusen-code/SaveRestrictedContentBot

**Comment by delivrance** [comment] 2023-04-09 06:41
The issue section on GitHub is only for issues happening within the library involving normal usages. The described issue doesn't involve normal usages and therefore I'm closing this. Furthermore, the issue report was inadequate since it lacked effort and a proper minimal, complete and reproducible example; whole code repositories are not such an example.

**Closed by delivrance** 2023-04-09 06:41 UTC
