### ISSUE TITLE
Client produce keyError while starting the bot

### ISSUE THREAD

**Issue by lmjaedentai** [pyrogram/pyrogram#1259] opened 2023-04-19 02:28 UTC
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

This error never happens before until recently during this week, when I run my bot.
My pyro bot can't login because of this error.

I tried to reinstall the module but it not works. Any help would be appreciated!

### Steps to reproduce

When I am starting my telegram bot by Pyrogram using the latest version `v2.0.103`
```py
app = Client("BillyKaiChengBot",api_id="apiid",api_hash=os.environ['API'],bot_token=os.environ['TOKEN'])
    
with app: #error produces here
    loginapp = app.send_message(channel_id, "login")

#my own code
#.
#.
#.
app.run()
```

### Logs

```shell
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    with app:
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/client.py", line 280, in __enter__
    return self.start()
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/client.py", line 584, in load_session
    await Auth(
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/session/auth.py", line 254, in create
    raise e
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/session/auth.py", line 89, in create
    res_pq = await self.invoke(raw.functions.ReqPqMulti(nonce=nonce))
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/session/auth.py", line 67, in invoke
    return self.unpack(response)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/session/auth.py", line 60, in unpack
    return TLObject.read(b)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
KeyError: 0
```

**Comment by delivrance** [comment] 2023-04-19 14:14
Duplicate of #1249.

**Closed** 2023-04-19 14:14 UTC
