### ISSUE TITLE
Better handling of sessions

### ISSUE THREAD

**Issue by surkum** [pyrogram/pyrogram#40] opened 2018-03-22 23:16 UTC
While downloading a great number of media files I'm getting this exception that is nor treated nor raised

```[420 FLOOD_WAIT_X]: A wait of 1369 seconds is required
Traceback (most recent call last):
  File "/home/user/tmp/telegram_backup/lib64/python3.6/site-packages/pyrogram/client/client.py", line 338, in download_worker
    progress=progress
  File "/home/user/tmp/telegram_backup/lib64/python3.6/site-packages/pyrogram/client/client.py", line 2143, in get_file
    dc_id=dc_id
  File "/home/user/tmp/telegram_backup/lib64/python3.6/site-packages/pyrogram/client/client.py", line 554, in send
    r = self.session.send(data)
  File "/home/user/tmp/telegram_backup/lib64/python3.6/site-packages/pyrogram/session/session.py", line 402, in send
    return self._send(data)
  File "/home/user/tmp/telegram_app/lib64/python3.6/site-packages/pyrogram/session/session.py", line 388, in _send
    Error.raise_it(result, type(data))
  File "/home/user/tmp/telegram_backup/lib64/python3.6/site-packages/pyrogram/api/errors/error.py", line 67, in raise_it
    )(x)
pyrogram.api.errors.exceptions.flood_420.FloodWait: [420 FLOOD_WAIT_X]: A wait of 1369 seconds is required
......
``` 

and the exception is reported again and again until flooding wait time pass, the file is downloaded and then it is raised again with every download command.

the code which produces the exception  is: 

`filename = client.download_media(message, block=True, file_name=name)`

**Comment by delivrance** [comment] 2018-03-22 23:26
What raises the FLOOD_WAIT_X error is ExportAuthorization.
The problem is that Pyrogram creates new keys for every file downloaded, and the server is limiting us in doing so. We should instead create one, cache it and re-use it when needed.

**Comment by delivrance** [comment] 2018-03-22 23:29
@surkum Can I ask you how many files have you tried to download? More or less. Just to get an idea of when such situation would occur.

**Comment by surkum** [comment] 2018-03-22 23:40
I was trying to backup a long conversation (14 messages), and all it's media files(~2000), it started to fail around 400

**Comment by delivrance** [comment] 2018-03-23 00:46
@surkum Hi. I've pushed some changes to a new branch. Use `pip3 install -U git+https://github.com/pyrogram/pyrogram@cache-sessions` to test this out and tell me how it goes.

**Comment by surkum** [comment] 2018-03-25 09:24
@delivrance I can confirm that the issue is solved with this patch, I've been able to download +3K media elements from a stream without problems. thx.

**Comment by delivrance** [comment] 2018-03-25 16:06
Let's keep this open as a reminder until is merged.

**Closed** 2018-06-01 12:06 UTC
Labels: enhancement

**Comment by enterFaisal** [comment] 2023-11-23 20:22
I also got the same error

```
File "/opt/python/pyrogram/client.py", line 870, in get_file
    exported_auth = await self.invoke(
  File "/opt/python/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/opt/python/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/opt/python/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/opt/python/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 833 seconds is required (caused by "auth.ExportAuthorization")
```
