### ISSUE TITLE
Not reconnecting after losing internet connection

### ISSUE THREAD

**Issue by superdoghercules** [pyrogram/pyrogram#674] opened 2021-04-30 08:55 UTC
## Checklist
- [X] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [X] I have searched in the issue tracker for similar bug reports, including closed ones.
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
The bot does not come back after the device disconnects from the internet. Looking at the logs I see that NetworkTask, Session etc has stopped.

## Steps to Reproduce
Run bot and disconnect internet. Reconnect internet after 30 seconds and bot remains dead due to internal tasks not running.

**Comment by delivrance** [comment] 2021-04-30 10:06
Since you didn't provide much information and not even a minimal example, I will assume the code below:

``` python
from pyrogram import Client
app = Client("bot")
app.run()
```

which doesn't reproduce the issue described on my machine as the bot comes back online automatically after having the connection shutdown for 30 seconds or more as suggested.

Closing as invalid since I can't reproduce the issue.

**Closed by delivrance** 2021-04-30 10:06 UTC
